### PR TITLE
Prepare for Python test fixtures

### PR DESCRIPTION
**Pull request by uranusjr**
Toward #27.

This adds a script to scrap wheel metadata on PyPI to “freeze” dependency information for test cases.

### CODE REVIEW

**Comment by uranusjr** [comment]
Alright, the script seems to work (albeit slow and with several hacks to make typing work), I’ll start adding test cases.

**Comment by uranusjr** [comment]
Python packages have surprisingly large number of dependencies (if we include intrinsic) if we count all package extras. A large portion of this problem is probably contributed by Python lacking a dedicated way to specify a project’s test/dev dependencies.

**Comment by pradyunsg** [comment]
Yup yup. At some point, we started suggesting that users use extra for development and testing dependencies. FWIW the resolver will have to resolve these instances too, so they are valid tests.

In some ways, the resolver should be doing what literally this script is doing, but "smarter".

**Comment by uranusjr** [comment]
Indeed. The script is left “dumb” intentionally to ensure the resolver implementation does the right thing. My comment was more about complaining the incredible size of the frozen index (compared to RubyGems).

**Comment by uranusjr** [comment]
Cool, seems like this thing is working, one test case down. Merging this and continue working on other fixtures.

**Pull request merged**
